version: '2'
services:
  lint:
    image: buildkite/plugin-linter
    command: [ '--id', 'elastic/oblt-cli' ]
    volumes:
      - ".:/plugin"
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/plugin:ro"
    environment:
      - GH_TOKEN
      - GITHUB_TOKEN
    command: ['bats', 'tests/unit']

  integration-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/plugin:ro"
    environment:
      - GH_TOKEN
      - GITHUB_TOKEN
    command: [ 'bats', 'tests/integration' ]
