#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/setup.bash
. "${DIR}/../lib/setup.bash"

GH_TOKEN="${BUILDKITE_PLUGIN_OBLT_CLI_GITHUB_TOKEN:-${GH_TOKEN:-${GITHUB_TOKEN:-}}}"
OBLT_CLI_USERNAME="${BUILDKITE_PLUGIN_OBLT_CLI_USERNAME}"
OBLT_CLI_SLACK_CHANNEL="${BUILDKITE_PLUGIN_OBLT_CLI_SLACK_CHANNEL}"
OBLT_CLI_VERSION="${BUILDKITE_PLUGIN_OBLT_CLI_VERSION}"
OBLT_CLI_VERSION_FILE="${BUILDKITE_PLUGIN_OBLT_CLI_VERSION_FILE}"

VERSION=$(get_version_from_file_or_fallback "${OBLT_CLI_VERSION_FILE}" "${OBLT_CLI_VERSION}")

echo "~~~ :elastic-apm: Set up oblt-cli ${VERSION}"

setup "${VERSION}" "${OBLT_CLI_USERNAME}" "${OBLT_CLI_SLACK_CHANNEL}" "${HOME}/.oblt-cli/bin"
